# Test against the latest version of this Node.js version
environment:
  version: 0.0.{build}

cache:
  - node_modules -> package.json

install:
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

for:
  -
    branches:
      only:
        - /release\/.*/
    after_deploy:
      - npm version %APPVEYOR_BUILD_VERSION%
      - "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII
      - npm publish