# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"
  version: 0.0.{build}

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'

build_script:
  - npm run build

test_script:
  - npm test

for:
  # override settings for `master` branch
  -
    branches:
      only:
        - master

    configuration: Release

    after_deploy:
      - npm publish